// implement MovieList component here
import React from 'react';

class MovieList extends React.Component {
  render() {
    return (
      <ul>
        <MovieList movies={ movies                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }/>
      </ul>
    );
  }
}

export default MovieList;